function A_op = linear_part_Asaddle(l1,l2,node_space, node_time)

Adiag = linear_part_A(l1,l2,node_space, node_time);
Anon_diag = 0*Adiag;
A_op = overoperator3...
    (Adiag, Anon_diag, Anon_diag,...
    Anon_diag, Adiag, Anon_diag,...
    Anon_diag, Anon_diag, Adiag);